version: '3.9'
services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: onlymvp
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
      target: dev
    env_file:
      - apps/api/.env
    depends_on:
      - postgres
    ports:
      - '3001:3001'
    volumes:
      - ./apps/api:/app/apps/api
      - ./packages:/app/packages
      - ./prisma:/app/prisma
      - api_uploads:/app/apps/api/uploads

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
      target: dev
    env_file:
      - apps/web/.env
    depends_on:
      - api
    ports:
      - '3000:3000'
    volumes:
      - ./apps/web:/app/apps/web
      - ./packages:/app/packages

volumes:
  pgdata:
  api_uploads:
